--- 
kind: pipeline
name: default
type: docker

steps: 
  - 
    name: tests
    commands: 
      - "pip3 install --upgrade ."
      - "cd test && python3.6 test.py"
    image: grisha85/umake:1
    pull: if-not-exists
  
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV
      required: true
      files:
        - "*.xml"
      paths:
        - test/coverage